### ISSUE TITLE
I would like to contribute

### ISSUE THREAD

**Issue by 31Sanskrati** [muhammadanas0716/LeetCodeTorture#12]
I solve LeetCode questions in **C++**. I want to contribute my solutions.

Is there anything I need to know before starting to contribute?

**Comment by muhammadanas0716** [comment]
Well firstly, I'm glad you are contributing. Just look under the Python/Easy folder and see how the question is solved. Your solution should be in a similar pattern. Once again thanks for contributing and I'm looking forward to your contribution.
